//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleResizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleResizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap FolderOpenBig {
            get {
                object obj = ResourceManager.GetObject("FolderOpenBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.jpg;*.jpeg;*.png;*.bmp.
        /// </summary>
        internal static string ImageFilePattern {
            get {
                return ResourceManager.GetString("ImageFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom margin:.
        /// </summary>
        internal static string MainFormMarginBottom {
            get {
                return ResourceManager.GetString("MainFormMarginBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left margin:.
        /// </summary>
        internal static string MainFormMarginLeft {
            get {
                return ResourceManager.GetString("MainFormMarginLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right margin:.
        /// </summary>
        internal static string MainFormMarginRight {
            get {
                return ResourceManager.GetString("MainFormMarginRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top margin:.
        /// </summary>
        internal static string MainFormMarginTop {
            get {
                return ResourceManager.GetString("MainFormMarginTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string MainFormPreviewWait {
            get {
                return ResourceManager.GetString("MainFormPreviewWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.{3}.
        /// </summary>
        internal static string MainFormTitle {
            get {
                return ResourceManager.GetString("MainFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value of {0} pixels is very high..
        /// </summary>
        internal static string MainFormValidateHeightBigMultiple {
            get {
                return ResourceManager.GetString("MainFormValidateHeightBigMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value of {0} pixels is very low..
        /// </summary>
        internal static string MainFormValidateHeightSmallMultiple {
            get {
                return ResourceManager.GetString("MainFormValidateHeightSmallMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value of one pixel is very low..
        /// </summary>
        internal static string MainFormValidateHeightSmallSingle {
            get {
                return ResourceManager.GetString("MainFormValidateHeightSmallSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With such a high margin value the stamp will be (partially) obscured..
        /// </summary>
        internal static string MainFormValidateMarginHHigh {
            get {
                return ResourceManager.GetString("MainFormValidateMarginHHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With a negative margin value the stamp will be (partially) obscured..
        /// </summary>
        internal static string MainFormValidateMarginHLow {
            get {
                return ResourceManager.GetString("MainFormValidateMarginHLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With such a high margin value the stamp will be (partially) obscured..
        /// </summary>
        internal static string MainFormValidateMarginVHigh {
            get {
                return ResourceManager.GetString("MainFormValidateMarginVHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With a negative margin value the stamp will be (partially) obscured..
        /// </summary>
        internal static string MainFormValidateMarginVLow {
            get {
                return ResourceManager.GetString("MainFormValidateMarginVLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resulting image quality is set very low..
        /// </summary>
        internal static string MainFormValidateQualityLow {
            get {
                return ResourceManager.GetString("MainFormValidateQualityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stamp&apos;s transparency is set very high. The stamp will not be visible..
        /// </summary>
        internal static string MainFormValidateStampTransparencyHigh {
            get {
                return ResourceManager.GetString("MainFormValidateStampTransparencyHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value of {0} pixels is very wide..
        /// </summary>
        internal static string MainFormValidateWidthBigMultiple {
            get {
                return ResourceManager.GetString("MainFormValidateWidthBigMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value of {0} pixels is very small..
        /// </summary>
        internal static string MainFormValidateWidthSmallMultiple {
            get {
                return ResourceManager.GetString("MainFormValidateWidthSmallMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value of one pixel is very small..
        /// </summary>
        internal static string MainFormValidateWidthSmallSingle {
            get {
                return ResourceManager.GetString("MainFormValidateWidthSmallSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	MsgProblemSolverClashCSFSingle	There are {0} items with the same destination file as other items in this project. With the option &apos;Create subfolders&apos; will these problems be solved. Do you want to enable this option? If not, these items will be skipped.	.
        /// </summary>
        internal static string MsgProblemSolverClashCSFMultiple {
            get {
                return ResourceManager.GetString("MsgProblemSolverClashCSFMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is one item with the same destination file as another item in this project. With the option &apos;Create subfolders&apos; will this problem be solved. Do you want to enable this option? If not, this item will be skipped..
        /// </summary>
        internal static string MsgProblemSolverClashCSFSingle {
            get {
                return ResourceManager.GetString("MsgProblemSolverClashCSFSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems.
        /// </summary>
        internal static string MsgProblemSolverClashCSFTitle {
            get {
                return ResourceManager.GetString("MsgProblemSolverClashCSFTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items with the same destination file as other items in this project.
        /// </summary>
        internal static string MsgProblemSolverClashMultiple {
            get {
                return ResourceManager.GetString("MsgProblemSolverClashMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one item with the same destination file as another item in this project.
        /// </summary>
        internal static string MsgProblemSolverClashSingle {
            get {
                return ResourceManager.GetString("MsgProblemSolverClashSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} items whose destination files already exist. Do you want to overwrite these files? If not, these items will be skipped..
        /// </summary>
        internal static string MsgProblemSolverDestExistsMultiple {
            get {
                return ResourceManager.GetString("MsgProblemSolverDestExistsMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is one item whose destination file already exists. Do you want to overwrite this file? If not, this item will be skipped..
        /// </summary>
        internal static string MsgProblemSolverDestExistsSingle {
            get {
                return ResourceManager.GetString("MsgProblemSolverDestExistsSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination file exists.
        /// </summary>
        internal static string MsgProblemSolverDestExistsTitle {
            get {
                return ResourceManager.GetString("MsgProblemSolverDestExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items which occur more than once in this project.
        /// </summary>
        internal static string MsgProblemSolverDupMultiple {
            get {
                return ResourceManager.GetString("MsgProblemSolverDupMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one item which occurs more than once in this project.
        /// </summary>
        internal static string MsgProblemSolverDupSingle {
            get {
                return ResourceManager.GetString("MsgProblemSolverDupSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following problems have been determined:.
        /// </summary>
        internal static string MsgProblemSolverIntro {
            get {
                return ResourceManager.GetString("MsgProblemSolverIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items whose source files could not be found.
        /// </summary>
        internal static string MsgProblemSolverNonExtMultiple {
            get {
                return ResourceManager.GetString("MsgProblemSolverNonExtMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one item whose source file could not be found.
        /// </summary>
        internal static string MsgProblemSolverNonExtSingle {
            get {
                return ResourceManager.GetString("MsgProblemSolverNonExtSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you continue, all these items will be skipped. Do you want to continue?.
        /// </summary>
        internal static string MsgProblemSolverOutro {
            get {
                return ResourceManager.GetString("MsgProblemSolverOutro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems.
        /// </summary>
        internal static string MsgProblemSolverTitle {
            get {
                return ResourceManager.GetString("MsgProblemSolverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled..
        /// </summary>
        internal static string MsgProcessCancelled {
            get {
                return ResourceManager.GetString("MsgProcessCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string MsgProcessCancelledTitle {
            get {
                return ResourceManager.GetString("MsgProcessCancelledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error has occured..
        /// </summary>
        internal static string MsgProcessError {
            get {
                return ResourceManager.GetString("MsgProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MsgProcessErrorTitle {
            get {
                return ResourceManager.GetString("MsgProcessErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished!.
        /// </summary>
        internal static string MsgProcessFinished {
            get {
                return ResourceManager.GetString("MsgProcessFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string MsgProcessFinishedTitle {
            get {
                return ResourceManager.GetString("MsgProcessFinishedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove every item from the list?.
        /// </summary>
        internal static string MsgProjectClearAll {
            get {
                return ResourceManager.GetString("MsgProjectClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all.
        /// </summary>
        internal static string MsgProjectClearAllTitle {
            get {
                return ResourceManager.GetString("MsgProjectClearAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination folder does not exist. Cannot continue..
        /// </summary>
        internal static string MsgProjectDestFolderNotFound {
            get {
                return ResourceManager.GetString("MsgProjectDestFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonexistant destination folder.
        /// </summary>
        internal static string MsgProjectDestFolderNotFoundTitle {
            get {
                return ResourceManager.GetString("MsgProjectDestFolderNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified new filename pattern &apos;{0}&apos; contains invalid fields (fields are those which start with &apos;%&apos;)..
        /// </summary>
        internal static string MsgProjectNewFilenamePatternInvalid {
            get {
                return ResourceManager.GetString("MsgProjectNewFilenamePatternInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New filename pattern.
        /// </summary>
        internal static string MsgProjectNewFilenamePatternInvalidTitle {
            get {
                return ResourceManager.GetString("MsgProjectNewFilenamePatternInvalidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified new filename pattern &apos;{0}&apos; would result in all the files getting the same filename. Use the &apos;%n&apos; and/or &apos;%c&apos; fields in the pattern..
        /// </summary>
        internal static string MsgProjectNewFilenamePatternYieldsSingleFilename {
            get {
                return ResourceManager.GetString("MsgProjectNewFilenamePatternYieldsSingleFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New filename pattern.
        /// </summary>
        internal static string MsgProjectNewFilenamePatternYieldsSingleFilenameTitle {
            get {
                return ResourceManager.GetString("MsgProjectNewFilenamePatternYieldsSingleFilenameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stampfile is not found. Cannot continue..
        /// </summary>
        internal static string MsgProjectStampNotFound {
            get {
                return ResourceManager.GetString("MsgProjectStampNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampfile not found.
        /// </summary>
        internal static string MsgProjectStampNotFoundTitle {
            get {
                return ResourceManager.GetString("MsgProjectStampNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current item: {0}
        ///	Items processed: {1} items
        ///	Items collected: {2} items.
        /// </summary>
        internal static string MsgStatusCollectingContent {
            get {
                return ResourceManager.GetString("MsgStatusCollectingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting subitems of {0} items.
        /// </summary>
        internal static string MsgStatusCollectingInstr {
            get {
                return ResourceManager.GetString("MsgStatusCollectingInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting.
        /// </summary>
        internal static string MsgStatusCollectingTitle {
            get {
                return ResourceManager.GetString("MsgStatusCollectingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string MsgStatusContent {
            get {
                return ResourceManager.GetString("MsgStatusContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy....
        /// </summary>
        internal static string MsgStatusInstr {
            get {
                return ResourceManager.GetString("MsgStatusInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;unknown&gt;.
        /// </summary>
        internal static string MsgStatusItemUnknown {
            get {
                return ResourceManager.GetString("MsgStatusItemUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current item: {0}
        ///	Items processed: {1} items
        ///	Items skipped: {2} items.
        /// </summary>
        internal static string MsgStatusProcessingContent {
            get {
                return ResourceManager.GetString("MsgStatusProcessingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} items.
        /// </summary>
        internal static string MsgStatusProcessingInstr {
            get {
                return ResourceManager.GetString("MsgStatusProcessingInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        internal static string MsgStatusProcessingTitle {
            get {
                return ResourceManager.GetString("MsgStatusProcessingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        internal static string MsgStatusTitle {
            get {
                return ResourceManager.GetString("MsgStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items validated: {0} items
        ///	Problems found: {1} problems.
        /// </summary>
        internal static string MsgStatusValidatingContent {
            get {
                return ResourceManager.GetString("MsgStatusValidatingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating {0} items.
        /// </summary>
        internal static string MsgStatusValidatingInstr {
            get {
                return ResourceManager.GetString("MsgStatusValidatingInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating.
        /// </summary>
        internal static string MsgStatusValidatingTitle {
            get {
                return ResourceManager.GetString("MsgStatusValidatingTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MultiFilesBig {
            get {
                object obj = ResourceManager.GetObject("MultiFilesBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file(s) en {1} folder(s).
        /// </summary>
        internal static string StatusBarItemCount {
            get {
                return ResourceManager.GetString("StatusBarItemCount", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap WarningIcon {
            get {
                object obj = ResourceManager.GetObject("WarningIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
